language: python
python:
  - '3.6'
  - '3.7'

before_script:
  - curl -s https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly

install:
    - pip install pipenv
    - pipenv install --skip-lock
    - python setup.py install
script:
    - py.test
    - black --check
