matrix:
    include:
        - language: python
          python:
              - '3.6'
              - '3.7'
        - language: rust
          rust:
              - nightly

install:
- pip install pipenv
- pipenv install --skip-lock
- python setup.py install
script:
- py.test
- black --check
