language: python
cache: false
python:
  - '3.6'
  - '3.7'

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y -v --default-toolchain nightly
  - source $HOME/.cargo/env

install:
    - pip install pipenv
    - pipenv install --skip-lock
      # - python setup.py install
    - pip install . -U
script:
    - py.test
    - black --check
