[package]
name = "gaussians"
version = "0.0.1"
edition = "2018"

[lib]
name = "gaussian_lib"
crate-type = ["cdylib"]

[dependencies]
numpy = "*"
gs-lib = { git = "ssh://git@github.com/Schoyen/gs-lib.git" }

[dependencies.pyo3]
version = "*"
features = ["extension-module"]
