[package]
name = "gaussians"
version = "0.0.1"
edition = "2018"

[lib]
name = "gaussian_lib"
crate-type = ["cdylib"]

[dependencies]
numpy = "*"
ndarray = "*"

[dependencies.pyo3]
version = "*"
features = ["extension-module"]
